### ISSUE TITLE
Changes with Font Awesome 6 Free

### ISSUE THREAD

**Issue by vaz-ar** [AngelCrawford/joplin-theme#4]
Hello,

I just tried your theme (which is very good) and wanted to let you now that I noticed a problem related to Font Awesome:
I went and downloaded the last Font Awesome version from the website linked, which is now font awesome 6, and when I tried your theme I noticed that the icons weren't working (for the messages templates).

I opened the CSS and noticed that it was referencing "Font Awesome 5 free", which was the reason for the icons not appearing.
I replaced 5 by 6 in the CSS and now success-message.md and help-message.md successfully display their icons, but the other templates icons are still broken.
~~I am not sure why this is happening, but it might be that the UTF-8 characters set as content in the CSS are not present any more in the version 6.~~ It looks like they are available on the website at least, so I really don't know.

Anyway, just wanted to let you know in case you planned to update to the last Font Awesome version at some point that there might be troubles.

**Comment by AngelCrawford** [comment]
Thank you very much! I will have a look at the Weekend about this :)

**Comment by AngelCrawford** [comment]
Update: Changed download link to version 5 in the readme. Will have a look into Version 6 when I have more time.

**Comment by AngelCrawford** [comment]
I updated all .css files and the readme for Font Awesome 6.4.0.
All Unicodes are working again, was a little bit tricky, but I got behind the problem.
